version: '3.6'
services:
  selenoid:
    network_mode: bridge
    image: "aerokube/selenoid:latest-release"
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid"
      - "//var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]