version: '2'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
  selenoid-ui:
    links:
      - selenoid
    network_mode: bridge
    image: aerokube/selenoid-ui
    ports:
      - "8080:8080"
    command: -selenoid-uri http://selenoid:4444